export default {
    products: [ // products is an array of products
        {
            _id: 's-4115072',
            name: 'Aishani Refined Kurti',
            category: 'Kurti',
            image: '/images/women/kurtiAndKurta/s-4115072.jpg',
            price: 653,
            rating: 4.5,
            numReviews: 10,
            countInStock: 6,
        },
        {
            _id: 's-4281109',
            name: "Women's Embroided Cotton Kurti",
            category: 'Kurti',
            image: '/images/women/kurtiAndKurta/s-4281109.jpg',
            price: 546,
            rating: 4.5,
            numReviews: 10,
            countInStock: 6,
        },
        {
            _id: 's-439632',
            name: ' Designer Party Wear Kurti',
            category: 'Kurti',
            image: '/images/women/kurtiAndKurta/s-439632.jpg',
            price: 640,
            rating: 4.5,
            numReviews: 10,
            countInStock: 6,
        },
        {
            _id: 's-4871863',
            name: "Women's Printed Cotton Blend Kurti",
            category: 'Kurti',
            image: '/images/women/kurtiAndKurta/s-4871863.jpg',
            price: 543,
            rating: 4.5,
            numReviews: 10,
            countInStock: 6,
        },
        {
            _id: 's-4115072',
            name: "Women's Printed Cotton Blend Kurti",
            category: 'Kurti',
            image: '/images/women/kurtiAndKurta/s-4115072.jpg',
            price: 653,
            rating: 4.5,
            numReviews: 10,
            countInStock: 6,
        },
        {
            _id: 's-4903084',
            name: "Hiba Gorgeous Faux Georgette Women's Kurti",
            category: 'Kurti',
            image: '/images/women/kurtiAndKurta/s-4903084.jpg',
            price: 773,
            rating: 4.5,
            numReviews: 10,
            countInStock: 6,
        },
        {
            _id: 's-4903817',
            name: 'Trendy Fashionable Kurti',
            category: 'Kurti',
            image: '/images/women/kurtiAndKurta/s-4903817.jpg',
            price: 781,
            rating: 4.5,
            numReviews: 10,
            countInStock: 6,
        },
        {
            _id: 's-4932723',
            name: "Women's Ethnic Motif Printed Rayon Kurti",
            category: 'Kurti',
            image: '/images/women/kurtiAndKurta/s-4932723.jpg',
            price: 622,
            rating: 4.5,
            numReviews: 10,
            countInStock: 6,
        },
        {
            _id: 's-5055834',
            name: 'Kashvi Stylish Women Kurti',
            category: 'Kurti',
            image: '/images/women/kurtiAndKurta/s-5055834.jpg',
            price: 548,
            rating: 4.5,
            numReviews: 10,
            countInStock: 6,
        },
        {
            _id: 's-5459272',
            name: 'Adrika Voguish Kurti',
            category: 'Kurti',
            image: '/images/women/kurtiAndKurta/s-5459272.jpg',
            price: 694,
            rating: 4.5,
            numReviews: 10,
            countInStock: 6,
        },
        {
            _id: 's-5563026',
            name: 'Attractive Women Kurti',
            category: 'Kurti',
            image: '/images/women/kurtiAndKurta/s-5563026.jpg',
            price: 629,
            rating: 4.5,
            numReviews: 10,
            countInStock: 6,
        },
        {
            _id: 's-5667788',
            name: 'Jivika Ensemble Kurti',
            category: 'Kurti',
            image: '/images/women/kurtiAndKurta/s-5667788.jpg',
            price: 504,
            rating: 4.5,
            numReviews: 10,
            countInStock: 6,
        },
        {
            _id: 's-6004749',
            name: 'Kashvi Stylish Women Kurti',
            category: 'Kurti',
            image: '/images/women/kurtiAndKurta/s-6004749.jpg',
            price: 548,
            rating: 4.5,
            numReviews: 10,
            countInStock: 6,
        },
        {
            _id: 's-6316061',
            name: 'Myra Drishya Kurti',
            category: 'Kurti',
            image: '/images/women/kurtiAndKurta/s-6316061.jpg',
            price: 622,
            rating: 4.5,
            numReviews: 10,
            countInStock: 6,
        },
        {
            _id: 's-6407359',
            name: 'Adrika Voguish Kurtis',
            category: 'Kurti',
            image: '/images/women/kurtiAndKurta/s-6407359.jpg',
            price: 685,
            rating: 4.5,
            numReviews: 10,
            countInStock: 6,
        },
        {
            _id: 's-6410765',
            name: 'Aakarsha Fabulous Kurti',
            category: 'Kurti',
            image: '/images/women/kurtiAndKurta/s-6410765.jpg',
            price: 711,
            rating: 4.5,
            numReviews: 10,
            countInStock: 6,
        },
        {
            _id: 's-6420658',
            name: 'Alisha Pretty Kurti',
            category: 'Kurti',
            image: '/images/women/kurtiAndKurta/s-6420658.jpg',
            price: 642,
            rating: 4.5,
            numReviews: 10,
            countInStock: 6,
        },
        {
            _id: 's-6631431',
            name: 'Mialo Anarkali Printed Kurti',
            category: 'Kurti',
            image: '/images/women/kurtiAndKurta/s-6631431.jpg',
            price: 712,
            rating: 4.5,
            numReviews: 10,
            countInStock: 6,
        },
        {
            _id: 's-6632272',
            name: 'Attractive Rayon Kurta',
            category: 'Kurti',
            image: '/images/women/kurtiAndKurta/s-6632272.jpg',
            price: 544,
            rating: 4.5,
            numReviews: 10,
            countInStock: 6,
        },
        {
            _id: 's-6859583',
            name: 'Aakarsha Fabulous Red Kurti',
            category: 'Kurti',
            image: '/images/women/kurtiAndKurta/s-6859583.jpg',
            price: 554,
            rating: 4.5,
            numReviews: 10,
            countInStock: 6,
        },
        {
            _id: 's-7087514',
            name: 'Aakarsha Fabulous Black Kurti',
            category: 'Kurti',
            image: '/images/women/kurtiAndKurta/s-7087514.jpg',
            price: 711,
            rating: 4.5,
            numReviews: 10,
            countInStock: 6,
        },
        {
            _id: 's-7107395',
            name: 'Myra Petite Kurti',
            category: 'Kurti',
            image: '/images/women/kurtiAndKurta/s-7107395.jpg',
            price: 512,
            rating: 4.5,
            numReviews: 10,
            countInStock: 6,
        },
        {
            _id: 's-7366916',
            name: 'Adrika Voguish Kurti',
            category: 'Kurti',
            image: '/images/women/kurtiAndKurta/s-7366916.jpg',
            price: 489,
            rating: 4.5,
            numReviews: 10,
            countInStock: 6,
        },
        {
            _id: 's-7457361',
            name: 'Charvi Refined Kurti',
            category: 'Kurti',
            image: '/images/women/kurtiAndKurta/s-7457361.jpg',
            price: 597,
            rating: 4.5,
            numReviews: 10,
            countInStock: 6,
        },
        {
            _id: 's-7601931',
            name: 'Myra Drishya Kurti',
            category: 'Kurti',
            image: '/images/women/kurtiAndKurta/s-7601931.jpg',
            price: 622,
            rating: 4.5,
            numReviews: 10,
            countInStock: 6,
        },
        {
            _id: 's-8086541',
            name: 'Adrika Voguish Kurti',
            category: 'Kurti',
            image: '/images/women/kurtiAndKurta/s-8086541.jpg',
            price: 683,
            rating: 4.5,
            numReviews: 10,
            countInStock: 6,
        },
        {
            _id: 's-8086546',
            name: 'Charvi Sensational Kurti',
            category: 'Kurti',
            image: '/images/women/kurtiAndKurta/s-8086546.jpg',
            price: 675,
            rating: 4.5,
            numReviews: 10,
            countInStock: 6,
        },
        {
            _id: 's-8777873',
            name: 'Ahisarika women kurti',
            category: 'Kurti',
            image: '/images/women/kurtiAndKurta/s-8777873.jpg',
            price: 784,
            rating: 4.5,
            numReviews: 10,
            countInStock: 6,
        },
    ],
};
